name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-lint:
    name: Test and Lint
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC and Ninja
        run: |
          case ${{ matrix.os }} in 
              ubuntu-latest)
              sudo apt-get update
              sudo apt-get install -y ninja-build gcc-13
              ;;
              macos-latest)
              brew install ninja
              brew install gcc@13
              ;;
              windows-latest)
              choco install ninja
              ;;
          esac

      - name: Compile and test
        run: |
          cmake \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS='-Wall -Wextra -Wpedantic' \
            -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wpedantic' \
            -G Ninja \
            -S . -B build
          cmake --build build
          cd ./build
          ctest
