name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-lint:
    name: Test and Lint
    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          case ${{ matrix.os }} in 
              ubuntu-24.04)
              sudo apt update
              sudo apt install -y ninja-build
              ;;
              macos-latest)
              brew install ninja
              brew install llvm
              ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format"
              ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
              ;;
              windows-latest)
              choco install ninja
              ;;
          esac

      - name: Compile and test
        run: |
          cmake \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_FLAGS='-Wall -Wextra -Wpedantic -Werror' \
            -DCMAKE_CXX_FLAGS='-Wall -Wextra -Wpedantic -Werror' \
            -G Ninja \
            -S . -B build
          cmake --build build
          cd ./build
          ctest
